AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configure ALB Listeners for HTTP to HTTPS Redirect and Forwarding'

Parameters:
  LoadBalancerArn:
    Type: String
    Description: ARN of the Application Load Balancer

  TargetGroupArn:
    Type: String
    Description: ARN of the Target Group

  HTTPListenerArn:
    Type: String
    Description: ARN of the HTTP Listener (Port 80)

  HTTPSListenerArn:
    Type: String
    Description: ARN of the HTTPS Listener (Port 443)

Resources:
  # Rule to redirect HTTP to HTTPS (on port 80)
  HTTPListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301
      Conditions:
        - Field: "path-pattern"
          Values:
            - "/*"
      ListenerArn: !Ref HTTPListenerArn
      Priority: 6

  # Rule for HTTPS listener to forward to target group (on port 443)
  HTTPSListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupArn
      Conditions:
        - Field: "path-pattern"
          Values:
            - "/*"
      ListenerArn: !Ref HTTPSListenerArn
      Priority: 6

Outputs:
  HTTPListenerArn:
    Description: ARN of the HTTP Listener
    Value: !Ref HTTPListenerArn

  HTTPSListenerArn:
    Description: ARN of the HTTPS Listener
    Value: !Ref HTTPSListenerArn
