AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for user-service microservice

Parameters:
  GitHubRepoUrl:
    Type: String
    Description: https://github.com/Prabhashi-Sharlyn/user-service
  BranchName:
    Type: String
    Default: automation
    Description: automation

Resources:
  UserServicePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: betterwellness-user-service-pipeline
      RoleArn: arn:aws:iam::123456789012:role/codepipeline-service-role
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: Prabhashi-Sharlyn
                Repo: user-service
                Branch: !Ref BranchName
                OAuthToken: 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
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref UserServiceCodeBuildProject
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName: user-service-app
                DeploymentGroupName: user-service-deployment-group

  CodePipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: user-service-pipeline-artifacts-bucket
